### ISSUE TITLE
Add missing solutions

### ISSUE THREAD

**Issue by priyanshisharma** [priyanshisharma/Leetcoding-Challenge#1]
I haven't been as active in the Leetcoding challenge lately, so anyone looking for places to contribute for the hacktoberfest is welcome to make a PR to any of the missing days, for the completeness of this repository.

A list of missing questions is as follows-

* **30 June** - https://leetcode.com/problems/word-search-ii/ - Taken by @apurvi96
* **24 July** - https://leetcode.com/problems/all-paths-from-source-to-target/ - Taken up by @ojas032
* **30 July** - https://leetcode.com/problems/word-break-ii/ - Taken up by @codewithnick
* **13 August** - https://leetcode.com/problems/iterator-for-combination/ - Taken by @shashwats538
* **18 August** - https://leetcode.com/problems/numbers-with-same-consecutive-differences/ - Taken by @meghnabajoria
* **22 August** - https://leetcode.com/problems/random-point-in-non-overlapping-rectangles/ - Taken by @SiddhantDugar
* **23 August** - https://leetcode.com/problems/stream-of-characters/ - Taken by @Valkyrie006
* **25 August** - https://leetcode.com/problems/minimum-cost-for-tickets/ - Taken by @ShreyashRoyzada
* **26 August** - https://leetcode.com/problems/fizz-buzz/ - Taken up by @sai-pothuri
* **27 August** - https://leetcode.com/problems/find-right-interval/ - Taken up by @srasti-0630 
* **28 August**  - https://leetcode.com/problems/implement-rand10-using-rand7/ - Taken by @aadityasohani
* **29 August** - https://leetcode.com/problems/pancake-sorting/ - Taken by @iamakshat01
* **30 August**  - https://leetcode.com/problems/largest-component-size-by-common-factor/ - Taken by @gayatri517
* **31 August**  - https://leetcode.com/problems/delete-node-in-a-bst/ - Taken by @gayatri517
* **1 September** - https://leetcode.com/problems/largest-time-for-given-digits/ - Taken by @UtkarshChaurasia
* **12 September** - https://leetcode.com/problems/combination-sum-iii/ - Taken up by @ojas032
* **13 September** - https://leetcode.com/problems/insert-interval/ - Taken by @apurvi96
* **16 September** - https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/ - Taken by @UtkarshChaurasia
* **17 September** - https://leetcode.com/problems/robot-bounded-in-circle/ - Taken by @iamakshat01

#### Additional Information
* Please make your PR from 1-31 October for it to count for Hacktoberfest.
* Please make the PR for only 1 or at max 2 problems only.
* Please comment the problems that you will be solving so that nobody else spends time on those.
* Please put the solution in appropriate folder with appropriate name (check out the repository to understand), I'll run the code to be sure that it works, and then merge your PR.
* Feel free to code in any language, though C++ is preferred.

Due to overwhelming response, I have decided to add more problems. you can check these out too!
* **19 September** - https://leetcode.com/problems/sequential-digits/ - Taken by @jainaayush01
* **20 September** - https://leetcode.com/problems/unique-paths-iii/ - Taken by @everlearner
* **23 September** -  https://leetcode.com/problems/gas-station/ - Taken by @MiKinshu
* **27 September** - https://leetcode.com/problems/evaluate-division/ - Taken by @incognito1729

If you weren't able to claim an issue, feel free to come back in a few weeks when I'll be happy to reassign problems in case of inactivity.

**Comment by codewithnick** [comment]
Hey i want to participate in hactoberfest can you guide me with what to do ,here?

**Comment by Durveshpal** [comment]
hey,
 I want to know also that what to do in this code

**Comment by priyanshisharma** [comment]
Sure @codewithnick @Durveshpal 

In my repository, I put solutions to questions that are a part of the Leetcode Challenge, so I have folders for every month and I add my solutions to them there. Since, I haven't been as regular lately and it is *hacktoberfest* I wanted to welcome new contributors, who could make a PR by solving a leetcode problem.

Above is a list of problems that I happened to skip, so if you solve any of these problems, you can make a PR to my repository with the solution to any of them. 

Please put the solution in appropriate folder with appropriate name, I'll run the code to be sure that it works, and then merge your PR.

**Comment by codewithnick** [comment]
Thanks so much can you assign the issue to me I'll have a look at the problems and  try to solve as much as I can.

Also I wanted to ask you what names should I give to the directories and files and how many pr's can I make  on this repo?thanks for your reply I'll start working as soon as I am assigned.

**Comment by priyanshisharma** [comment]
Hey @codewithnick I won't be assigning this issue to anyone as I don't expect anyone to solve all the questions, I rather expect you to solve not more than one, or maybe two or three questions max. 
This is because I want my repository to remain open to contributions and I will also try to solve these myself, trying to make my repository *complete* by end of October.

Feel free to comment the question(s) you would like to solve, so that nobody else solves it. I will also update the Issue description accordingly.

Check out the repository and you should understand the folder structure. Like September's solution go in a folder called September, August in August etc. The name of the file is mostly like `Month_Date_Name_of_Question.cpp` Eg. `July_04_Ugly_Number_II.cpp`

**Comment by sai-pothuri** [comment]
Hello!
I would like to solve one or two questions here:) 
Can I proceed to do that?

**Comment by priyanshisharma** [comment]
Sure @sai-pothuri, please mention which questions you are solving as well so that nobody else does them.

**Comment by sai-pothuri** [comment]
Yep I'll do that as soon as i look into them @priyanshisharma

**Comment by sai-pothuri** [comment]
Also @priyanshisharma is it okay if I code the problems in python or do you want it to be only in C++?

**Comment by ojas032** [comment]
Hey @priyanshisharma I am working on  All Paths From Source to Target and  Combination Sum III

**Comment by codewithnick** [comment]
> Hey @codewithnick I won't be assigning this issue to anyone as I don't expect anyone to solve all the questions, I rather expect you to solve not more than one, or maybe two questions max.
> This is because I want my repository to remain open to contributions and I will also try to solve these myself, trying to make my repository _complete_ by end of October.
> 
> Feel free to comment the question(s) you would like to solve, so that nobody else solves it. I will also update the Issue description accordingly.
> 
> Check out the repository and you should understand the folder structure. Like September's solution go in a folder called September, August in August etc. The name of the file is mostly like `Month_Date_Name_of_Question.cpp` Eg. `July_04_Ugly_Number_II.cpp`

thank you i will be working on 
30 July - https://leetcode.com/problems/word-break-ii/

**Comment by codewithnick** [comment]
i am trying to solve it in python is that okay

**Comment by priyanshisharma** [comment]
Updated @ojas032 and @codewithnick 🙌 
Yes, feel free to solve it in python @codewithnick @sai-pothuri

**Comment by sai-pothuri** [comment]
I'll start working on 
26 August - https://leetcode.com/problems/fizz-buzz/

**Comment by UtkarshChaurasia** [comment]
Hey @priyanshisharma I want to work on 1 September(largest time for given digits) and 16 September(Max XOR of 2 numbers) so can you please assign these to me?

**Comment by gayatri517** [comment]
Hi @priyanshisharma I would like to work on 30 Aug(largest component by size) and 31 Aug(delete node in BST) could you please assign it to me.

**Comment by The-14th-ZeuS** [comment]
Is it okay if I can come up with my own C++ solutions for some problems which are being solved in other languages?

**Comment by meghnabajoria** [comment]
Hey @priyanshisharma ! Please assign me - Numbers With Same Consecutive Differences. Thank you :)

**Comment by priyanshisharma** [comment]
@The-14th-ZeuS while I intend to add C++ solutions for them for myself later on, I don't think that is required right now.

**Comment by The-14th-ZeuS** [comment]
That's okay, thanks for taking the time to reply.

**Comment by ShreyashRoyzada** [comment]
Hey!
Can you please assign me Minimum Cost of Tickets. It's the question from 25th August.

Cheers

**Comment by apurvi96** [comment]
Hi @priyanshisharma  I would like to contribute for Hacktoberfest 2020 through ur repo want to take up the problem Word Search II (30 June)

**Comment by apurvi96** [comment]
hi @priyanshisharma  I would also like to take up the problem insert interval(13 September)

**Comment by aadityasohani** [comment]
hi @priyanshisharma I would like to contribute to  hacktoberfest 2020 through your repo with question:  **_28 August - https://leetcode.com/problems/implement-rand10-using-rand7/_**

**Comment by shashwats538** [comment]
hey @priyanshisharma , I'd like to work on the 13th August Problem. Can you please assign me to that?

**Comment by iamakshat01** [comment]
hi @priyanshisharma , I would like to work on the  29th august and 17th september problem. Can you please assign me to them?

**Comment by SiddhantDugar** [comment]
Hi @priyanshisharma , I am willing to work on one problem from these three : 
1. 13 August - https://leetcode.com/problems/iterator-for-combination/
2. 22 August - https://leetcode.com/problems/random-point-in-non-overlapping-rectangles/
3. 27 August - https://leetcode.com/problems/find-right-interval/
Can you please assign me to one of them?

**Comment by kashika3101** [comment]
Hi @priyanshisharma  , I am willing to work in c++ on one of the problems from the following :
1.)29 August - https://leetcode.com/problems/pancake-sorting/
2.)17 September - https://leetcode.com/problems/robot-bounded-in-circle/

Please assign me the issues respectively.

**Comment by venkateshSV** [comment]
Hi @priyanshisharma 
I would love to solve (**PANCAKE SORTING**) 29 August - https://leetcode.com/problems/pancake-sorting/

**Comment by Valkyrie006** [comment]
@priyanshisharma Can I get work on this problem as part of Hackroberfest https://leetcode.com/problems/pancake-sorting/ ?

**Comment by MiKinshu** [comment]
Hi! I am willing to work on 
* 23 August - https://leetcode.com/problems/stream-of-characters/

**Comment by MiKinshu** [comment]
Hi!
Can I work on * 17 September - https://leetcode.com/problems/robot-bounded-in-circle/

**Comment by jainaayush01** [comment]
Hi @priyanshisharma would love to participate to hacktoberfest through your repo.
Would love to solve the pancake sorting problem.
"29 August - https://leetcode.com/problems/pancake-sorting/ ".

**Comment by priyanshisharma** [comment]
> Hi @priyanshisharma , I am willing to work on one problem from these three :
> 
> 1. 13 August - https://leetcode.com/problems/iterator-for-combination/
> 2. 22 August - https://leetcode.com/problems/random-point-in-non-overlapping-rectangles/
> 3. 27 August - https://leetcode.com/problems/find-right-interval/
>    Can you please assign me to one of them?

I have assigned you **22 August - https://leetcode.com/problems/random-point-in-non-overlapping-rectangles/**

**Comment by srasti-0630** [comment]
Hi @priyanshisharma I am willing to solve **27 August - https://leetcode.com/problems/find-right-interval/**. Can I work on this?

**Comment by priyanshisharma** [comment]
@kashika3101 these problems have already been taken up by @iamakshat01. Please take up some other problem.
@MiKinshu 23rd August has already been claimed by @Valkyrie006 and 17 September by @iamakshat01 .
@jainaayush01 Pancake sorting has already been taken up by @iamakshat01

Feel free to check a question among the following
* **19 September** - https://leetcode.com/problems/sequential-digits/
* **20 September** - https://leetcode.com/problems/unique-paths-iii/
* **23 September** -  https://leetcode.com/problems/gas-station/
* **27 September** - https://leetcode.com/problems/evaluate-division/

**Comment by jainaayush01** [comment]
Ok than can you assign me the below question:
19 September - https://leetcode.com/problems/sequential-digits/

**Comment by MiKinshu** [comment]
Can I please solve 23 September - https://leetcode.com/problems/gas-station/

**Comment by incognito1729** [comment]
@priyanshisharma  can I please solve 27 September - https://leetcode.com/problems/evaluate-division/

**Comment by everlearner** [comment]
@priyanshisharma Can I solve 20th Sept https://leetcode.com/problems/unique-paths-iii/

**Comment by bdyutish** [comment]
@priyanshisharma would like to take up 19 September - https://leetcode.com/problems/sequential-digits/

**Comment by kashika3101** [comment]
> @kashika3101 these problems have already been taken up by @iamakshat01. Please take up some other problem.
> @MiKinshu 23rd August has already been claimed by @Valkyrie006 and 17 September by @iamakshat01 .
> @jainaayush01 Pancake sorting has already been taken up by @iamakshat01
> 
> Feel free to check a question among the following
> 
> * **19 September** - https://leetcode.com/problems/sequential-digits/
> * **20 September** - https://leetcode.com/problems/unique-paths-iii/
> * **23 September** -  https://leetcode.com/problems/gas-station/
> * **27 September** - https://leetcode.com/problems/evaluate-division/

can you please assign me 23 September - https://leetcode.com/problems/gas-station/

**Comment by priyanshisharma** [comment]
I'm sorry @bdyutish and @kashika3101 , all problems have been taken up! Please feel free to check back in a few week(s) and  if any of the participants do not solve their problem, I'll happily reassign it to you! 🍀 
Inconvenience is regretted! 😞

**Comment by ShivangiRai1310** [comment]
Hi @priyanshisharma 
Would love to participate in hacktoberfest through your repo. Looks like all problems have already been assigned.
Waiting for new problems to be added and to work on them.

**Comment by priyanshisharma** [comment]
Thank you for your interest @ShivangiRai1310 , I'll keep you in loop if I add any 🚀

**Comment by rishabh15b** [comment]
Hello @priyanshisharma 
I am willig to work on september-leetcode-challenge.
Can u please assign this to me?
- **Day 25** [ https://leetcode.com/problems/largest-number/]

**Comment by Rituraj-commits** [comment]
Hi @priyanshisharma 
Would love to make at least one PR from your repo but looks like all your problems are taken. Hoping for new problems.

**Comment by shibrahmachari** [comment]
hi @priyanshisharma Is there any problem left you can assign?

**Comment by chelsi-001011** [comment]
hey @priyanshisharma  Are there more problems?

**Comment by Sambhu98** [comment]
I would like to contribute, can you help me with getting started?

**Comment by cenation007** [comment]
Hey @priyanshisharma I will be working on 18 August problem <[https://leetcode.com/problems/numbers-with-same-consecutive-differences/](url). So could you please assign me that ?

**Comment by sanchit28** [comment]
I would like to do this question:https://leetcode.com/problems/fizz-buzz/

**Comment by sanchit28** [comment]
can I??

**Comment by Deepak290701** [comment]
Hi @priyanshisharma ,  i would like to contribute to your repo can you please assign me a problem .

**Comment by probhav** [comment]
I'll like to claim the issue. Would be glad to contribute!

**Comment by singhalpranav22** [comment]
Hi @priyanshisharma . Please assign some question. Glad to contribute as a good cp programmer.

**Comment by princekalra** [comment]
i would like to contribute on 30 june question can i??

**Comment by SameerRastogi00** [comment]
hi @priyanshisharma can you pls allot  me a question as well

**Comment by RajawatBanna** [comment]
I also want to contribute for this. 
Can you add some more question on this. @priyanshisharma

**Comment by Pranjal81** [comment]
Is there any problem left for which I can contribute? @priyanshisharma

**Comment by shreyanshi2228** [comment]
hi @ojas032 can I take 24 July - https://leetcode.com/problems/all-paths-from-source-to-target/ - Taken up by @ojas032
this issue?

**Comment by Aastha26-lab** [comment]
Hi @priyanshisharma ... I am willing to solve & contribute to your repo ... can you pls assign me any question ?

**Comment by Yash1256** [comment]
Hi @priyanshisharma .. I am also willing to solve and Contribute to your repo, So can u please assign me a question??

**Comment by Rahul171201** [comment]
HI @priyanshisharma .. I am new to this community hence want to contribute , is there something you can assign to me?

**Comment by Rishabh186** [comment]
I love to participate in Hacktoberfest 2020 through your repo, So can u please assign me a problem?

**Comment by kashikaadarsh** [comment]
Hey @priyanshisharma  can I solve August 8th Problem Path Sum III?

**Comment by jainaayush01** [comment]
Hey @priyanshisharma i Have completed the question assigned to me and had made the PR. Thank you for the support and please let me know if there is something more i can help.

**Comment by priyanshisharma** [comment]
@kashikaadarsh @Rishabh186 @Rahul171201 @Yash1256 @Aastha26-lab @shreyanshi2228 @Pranjal81 @RajawatBanna @SameerRastogi00 @princekalra @singhalpranav22 @probhav @Deepak290701 @cenation007 @sanchit28 @Rituraj-commits @shibrahmachari @chelsi-001011 @rishabh15b 

Thank you so much guys for your overwhelming support and enthusiasm, but I don't intend to open any new problems for hacktoberfest. I might reassign tasks from people if they haven't solved them. I shall release a list of the same if required on 7th October.

I'll raise a new issue if required and tag you all in the comments! Thanks!

**Comment by importsonu** [comment]
Hi @priyanshisharma !
Are you accepting solutions for the October 2020 leetcoding challenge as well?

**Comment by isrivastav99** [comment]
Hi @priyanshisharma !
Considering all the existing issues are taken up, are you still looking for contributions?

**Comment by codewithnick** [comment]
hey if anyone wants to work on the *30th july problem* can work on it.(I was working on it previously)
I was not able to crack all the test cases , but I have made 4 Prs for hacktoberfest anyways on another repository.
thanks for assigning this to me ,I am sorry I was not able to solve it

**Comment by codewithnick** [comment]
also if anyone wants mu solution for the problem can mail me /@ "nikhilsingh526452@gmail.com"

**Comment by priyanshisharma** [comment]
It is totally okay @codewithnick 👍

**Comment by priyanshisharma** [comment]
@importsonu Yes I am.
@isrivastav99 feel free to look for any missing solutions in the repo.
