### ISSUE TITLE
Adding April LeetCode Questions

### ISSUE THREAD

**Issue by gowrijp** [priyanshisharma/Leetcoding-Challenge#54]
Hi,
Would you be willing to add April Leetcode challenge questions too in this repository? I would love to contribute to it. 
Also, there are other questions that are pretty good and can be classified topic-wise or according to difficulty level like easy, medium, and hard and hence this repository could serve as a complete Leetcode solution archive! 
Would love to hear your views on the same.

**Comment by priyanshisharma** [comment]
Woah, I didn't think of that and it makes a lot of sense, will definitely like to do that!

**Comment by priyanshisharma** [comment]
April 1 - https://leetcode.com/problems/single-number/
April 2 - https://leetcode.com/problems/happy-number/
April 3 - https://leetcode.com/problems/maximum-subarray/
April 4 - https://leetcode.com/problems/move-zeroes/
April 5 - https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/
April 6 - https://leetcode.com/problems/group-anagrams/
April 8 - https://leetcode.com/problems/middle-of-the-linked-list/
April 9 - https://leetcode.com/problems/backspace-string-compare/
April 10 - https://leetcode.com/problems/min-stack/
April 11 - https://leetcode.com/problems/diameter-of-binary-tree/
April 12 - https://leetcode.com/problems/last-stone-weight/
April 13 - https://leetcode.com/problems/contiguous-array/
April 15 - https://leetcode.com/problems/product-of-array-except-self/
April 16 - https://leetcode.com/problems/valid-parenthesis-string/
April 17 - https://leetcode.com/problems/number-of-islands/
April 18 - https://leetcode.com/problems/minimum-path-sum/
April 19 - https://leetcode.com/problems/search-in-rotated-sorted-array/
April 20 - https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/
April 22 - https://leetcode.com/problems/subarray-sum-equals-k/
April 23 - https://leetcode.com/problems/bitwise-and-of-numbers-range/
April 24 - https://leetcode.com/problems/lru-cache/
April 25 - https://leetcode.com/problems/jump-game/
April 26 - https://leetcode.com/problems/longest-common-subsequence/
April 27 - https://leetcode.com/problems/maximal-square/
April 29 - https://leetcode.com/problems/binary-tree-maximum-path-sum/

**Comment by priyanshisharma** [comment]
@kashikaadarsh @Rishabh186 @Rahul171201 @Yash1256 @Aastha26-lab @shreyanshi2228 @Pranjal81 @RajawatBanna @SameerRastogi00 @princekalra @singhalpranav22 @probhav @Deepak290701 @cenation007 @sanchit28 @Rituraj-commits @shibrahmachari @chelsi-001011 @rishabh15b @ShivangiRai1310 @bdyutish and @kashika3101

**Comment by RajawatBanna** [comment]
hey @priyanshisharma  
please assign me

April 2 - https://leetcode.com/problems/happy-number/
April 3 - https://leetcode.com/problems/maximum-subarray/

**Comment by Rituraj-commits** [comment]
Thanks @priyanshisharma for the questions 
Assign me

April 22 - https://leetcode.com/problems/subarray-sum-equals-k/

April 29 - https://leetcode.com/problems/binary-tree-maximum-path-sum/

**Comment by Rahul171201** [comment]
Thanks @priyanshisharma for questions.
Please assign me 
April 1-  https://leetcode.com/problems/single-number/
April 22 - https://leetcode.com/problems/subarray-sum-equals-k/

**Comment by Deepak290701** [comment]
Thanks @priyanshisharma for the questions.
Please aasign me  
April 17 - https://leetcode.com/problems/number-of-islands/
April 24 -  https://leetcode.com/problems/lru-cache/

**Comment by shibrahmachari** [comment]
hey 
@priyanshisharma  please assign to me:
April 4 - https://leetcode.com/problems/move-zeroes/
April 5 - https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/
April 6 - https://leetcode.com/problems/group-anagrams/
April 8 - https://leetcode.com/problems/middle-of-the-linked-list/
April 15 - https://leetcode.com/problems/product-of-array-except-self/

**Comment by Aastha26-lab** [comment]
Thanks @priyanshisharma for uploading more questions.
Please assign me
April 11-https://leetcode.com/problems/diameter-of-binary-tree/
April 12-https://leetcode.com/problems/last-stone-weight/
April 25-https://leetcode.com/problems/jump-game/

**Comment by cenation007** [comment]
Thanks @priyanshisharma for these questions.
I would like to work on these questions.
April 19 - <https://leetcode.com/problems/search-in-rotated-sorted-array/>
April 13 - <https://leetcode.com/problems/contiguous-array/>
April 5 -< https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/>

**Comment by Pranjal81** [comment]
> 
> 
> @kashikaadarsh @Rishabh186 @Rahul171201 @Yash1256 @Aastha26-lab @shreyanshi2228 @Pranjal81 @RajawatBanna @SameerRastogi00 @princekalra @singhalpranav22 @probhav @Deepak290701 @cenation007 @sanchit28 @Rituraj-commits @shibrahmachari @chelsi-001011 @rishabh15b @ShivangiRai1310 @bdyutish and @kashika3101

thanks for more problems, please assign me April 5 and April 8. @priyanshisharma

**Comment by gowrijp** [comment]
Hi,
Thanks a lot @priyanshisharma for your consideration
April 25 - https://leetcode.com/problems/jump-game/
April 26 - https://leetcode.com/problems/longest-common-subsequence/
April 27 - https://leetcode.com/problems/maximal-square/
April 29 - https://leetcode.com/problems/binary-tree-maximum-path-sum/
Would love to add these..
Please assign me

**Comment by bdyutish** [comment]
Thanks a lot for more questions! Please assign me any leftover questions! Thanks!

**Comment by SameerRastogi00** [comment]
Thanks a lot @priyanshisharma  for the new questions . Please assign me any questions

**Comment by priyanshisharma** [comment]
I highly appreciate everyone'e enthusiasm but please restrict your contributions to only 2 questions per person. I have assigned it accordingly, please check your questions before solving 🚀

**Comment by Yash1256** [comment]
@priyanshisharma My Name was not There and also I have commented on the Previous Issues but not got any question's assigned but when saw this Issue I am Sorry that I not paid attention on the Names. So if u want to merge you can or else Close the PR I will make another one when the question will be assigned.
Thanks @priyanshisharma for adding more questions.

**Comment by princekalra** [comment]
please assign me https://leetcode.com/problems/minimum-path-sum/
and
https://leetcode.com/problems/maximal-square/

**Comment by everlearner** [comment]
Hey @priyanshisharma ! Can I take the April 27 - https://leetcode.com/problems/maximal-square/ ?

**Comment by Aastha26-lab** [comment]
Hey @priyanshisharma I am unable to figure out the location of the repository containing April questions ... can you pls tell the location of the repository so that I can make my Pr?

**Comment by Aastha26-lab** [comment]
@all if anyone know about the location of the repository .. pls tell me

**Comment by priyanshisharma** [comment]
@Yash1256 I highly appreciate your attitude 🚀 
There are is still April 23 - https://leetcode.com/problems/bitwise-and-of-numbers-range/ thats unassigned, would you like to take that?

**Comment by priyanshisharma** [comment]
@Aastha26-lab just make a folder called `April` and put your solution there.

**Comment by priyanshisharma** [comment]
@everlearner I'm sorry that has already been assigned to @princekalra but I'll be happy to reassign if he doesn't make his PR in the next few days.

**Comment by Yash1256** [comment]
> @Yash1256 I highly appreciate your attitude 🚀 
> There are is still April 23 - https://leetcode.com/problems/bitwise-and-of-numbers-range/ thats unassigned, would you like to take that?

Yes ma'am I will update a PR with the solution of the above question

**Comment by princekalra** [comment]
mam in which file i have to push the solution actually no folder of april LeetCode

**Comment by Yash1256** [comment]
@princekalra 
> in which file i have to push the solution actually no folder of april LeetCode

Simply make a `April` Folder and start Pushing your assigned Work.

**Comment by Yash1256** [comment]
@priyanshisharma ma'am any Update?

**Comment by priyanshisharma** [comment]
@Yash1256 update regarding?

**Comment by Adarsh08X** [comment]
Are there any leftover problems that i can take on ?

**Comment by priyanshisharma** [comment]
@Adarsh08X feel free to check for missing questions in the repository.
