### ISSUE TITLE
Add Missing Solutions

### ISSUE THREAD

**Issue by priyanshisharma** [priyanshisharma/Leetcoding-Challenge#92]
Feel free to check for any missing **Leetcode Challenge** questions in the repository and make a PR for the same.
* https://leetcode.com/explore/challenge/card/30-day-leetcoding-challenge/
* https://leetcode.com/explore/challenge/card/may-leetcoding-challenge/
* https://leetcode.com/explore/challenge/card/june-leetcoding-challenge/
* https://leetcode.com/explore/challenge/card/july-leetcoding-challenge/
* https://leetcode.com/explore/challenge/card/august-leetcoding-challenge/
* https://leetcode.com/explore/challenge/card/september-leetcoding-challenge/
* https://leetcode.com/explore/challenge/card/october-leetcoding-challenge/

**Comment by kaushik27mishra** [comment]
Is there any issue which is availble for me?

**Comment by kaushik27mishra** [comment]
A solution of April Leetcode challenge is missing. Can I proceed ahead to add it? 
[Day 18 - Minimum Path Sum](https://leetcode.com/explore/challenge/card/30-day-leetcoding-challenge/530/week-3/3303/)

**Comment by priyanshisharma** [comment]
Sure @kaushik27mishra 🙌

**Comment by Nitish-web-nik** [comment]
**I have completed the buddy string problem statement of Week 2: October 8th - October 14th using Java, should I add it?**

**Comment by priyanshisharma** [comment]
Sorry @Nitish-web-nik , please try to pick a fresh problem.
